scopes:
    - openid
    - profile
    - offline_access
    - user.read 
    - user.read.all 
    - files.read.all 
    - group.read.all 
    - sites.read.all 
    - groupmember.read.all 
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
